language: java

# Analyst Server requires Java 8 and Travis doesn't (yet) support OpenJDK 8
jdk:
  - oraclejdk8

# AWS access keys to download codedeploy templates
env:
  global:
    - secure: "Kn7TpT3qlTlTgVH3H6VyAl4KmFVSmgQ6sx26NT2hrHyX2YmXexCGFQzg5rLIu/LQ9PY0Mi9Kvjv44a7r+wyA6/ochnETRcVwSRi6znLttTODlIgp389wgFAvRdsx1/rD9MqhcsONack57I4vorX/2kWSchOOxGcYViGUYnNyeHA="
    - secure: "CQ6izYCP3pPZUTpSycD33OQKH8OEwijaXjTJ/pN3N3Q11Er7bNLIxPgoksNDAr4DzciPDCcftKr2PRIP4qD/QKcSX/zSNRbJcx7uuY10Y+zZ0NJieK/S1Ao/sW3HozuldBmNFrfsnFbzm/92Xqa3x5ZBaDaWsoxwxyUY3ah6M8s="

# We need the AWS CLI to get the codedeploy files
# see https://github.com/travis-ci/travis-ci/issues/3139
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

# We need to build OTP off a specific branch
install:
  - git clone --depth 1 --branch bootstrap https://github.com/opentripplanner/OpenTripPlanner.git
  - cd OpenTripPlanner
  - mvn package install -DskipTests
  - cd ..

# Run on container based infrastructure (allows caching &c.)
sudo: false

# Make a CodeDeploy deployment object
after_success:
  # build the package, but no need to run tests again
  - mvn package -DskipTests
  - mkdir shaded
  - cd shaded
  # get the CodeDeploy appspec and start/stop scripts from S3
  # They are stored outside the repo
  - aws s3 sync s3://analyst-codedeploy-eu/analyst-server/ .

  - mv ../target/analyst-server.jar .
  # don't confuse travis
  - cd ..

# Deploy artifacts to AWS CodeDeploy from master
deploy:
  - provider: codedeploy
    bucket: analyst-codedeploy-eu
    key: analyst-server-master.zip
    skip_cleanup: true
    application: analyst-server-master
    deployment_group: analyst-dev
    region: eu-west-1

    # upload from the specialized directory we just made
    local_dir: shaded

    on:
      branch: master
      repo: conveyal/analyst-server

    # Encrypted AWS access info
    # Travis generates a private key per repository. You can then encrypt values with the public key so only Travis can decrypt them
    access_key_id: &1
      secure: O4gTlHPCU8kjEl1MrvYRMsX94mC9H5mSUks6AmnY6vJTc/kYWsCUOdQSo2zjlilM6p20duEiuuLN7uEEq+1Mc99SMR8rN59T/tiobYxJPnRWmUObcgMSznEmxWxXzCkTh7kTVdA0cewLKMpun04+ekvy6CeTeqUo2PPa9eorrbU=
    secret_access_key: &2
      secure: bRDOfGvi6DcQZ6BuAIAK/TgVEl4RHltrw8q+bkcExe9PA+eQh809a3LYokIk4DHKLoiYbIKiCvss7argZZEVLIwb55kL5VoL/LPhf5P8Yns63XByiqr7XJJFehJdPaYiMmdPLUOrtgbv9nzD0J/W/NI/E1qfGvegwdEWtm4hSoQ=

  - provider: s3
    bucket: analyst-codedeploy-eu
    local_dir: dpl_cd_upload

    on:
      branch: master
      repo: conveyal/analyst-server

    access_key_id: *1
    secret_access_key: *2

    region: eu-west-1

# Save the maven cache to speed up builds (without this they take ~20 minutes while Maven downloads all the dependencies for OTP)
cache:
  directories:
    - "$HOME/.m2/repository"
